name: 'dbt_labal_pro'
version: '1.0'
config-version: 2
profile: 'LUCASABAL'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_labal_pro:
    staging:
      +schema: PL_STAGING
      +materialized: table
      +tags: ["staging"]

    marts:
      intermediate:
        +schema: PL_INTERMEDIATE
        +materialized: view
        +tags: ["intermediate", "marts"]

      business:
        +schema: PL_BUSINESS
        +materialized: table
        +tags: ["business", "marts"]

flags:
  require_generic_test_arguments_property: true